Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,6 +1,6 @@
 name: Build, Test and Deploy a .NET Core WebApi to Azure App Service
 
-env:
+env: # Change these settings when you need to
   ARTIFACT_NAME: WebApi
   DOTNET_CORE_VERSION: 8.0.x
   PUBLISH_DIRECTORY: "./out/publish"
@@ -11,11 +11,10 @@ on:
       - main
       - deployment
       - master
-  workflow_dispatch:
+  workflow_dispatch: 
 
 jobs:
   check:
-    name: 🔐 Check if required secrets exist
     runs-on: ubuntu-latest
     steps:
       - name: "Check if AZURE_WEBAPP_NAME secret exists"
@@ -24,7 +23,7 @@ jobs:
         if: ${{ env.super_secret == '' }}
         run: |
           echo "❌ Secret AZURE_WEBAPP_NAME is missing."
-          echo "➡️ Go to settings > Actions secrets and variables > Actions to create it."
+          echo "➡️ Maak hem aan bij Settings > Actions secrets and variables > Actions."
           exit 1
 
       - name: "Check if AZURE_WEBAPP_PUBLISH_PASSWORD secret exists"
@@ -33,7 +32,7 @@ jobs:
         if: ${{ env.super_secret == '' }}
         run: |
           echo "❌ Secret AZURE_WEBAPP_PUBLISH_PASSWORD is missing."
-          echo "➡️ Go to settings > Actions secrets and variables > Actions to create it."
+          echo "➡️ Maak hem aan bij Settings > Actions secrets and variables > Actions."
           exit 1
 
       - name: "Check if AZURE_WEBAPP_PUBLISH_USERNAME secret exists"
@@ -42,7 +41,7 @@ jobs:
         if: ${{ env.super_secret == '' }}
         run: |
           echo "❌ Secret AZURE_WEBAPP_PUBLISH_USERNAME is missing."
-          echo "➡️ Go to settings > Actions secrets and variables > Actions to create it."
+          echo "➡️ Maak hem aan bij Settings > Actions secrets and variables > Actions."
           exit 1
 
       - name: "Check if WEBAPI_PROJECT_NAME secret exists"
@@ -51,16 +50,14 @@ jobs:
         if: ${{ env.super_secret == '' }}
         run: |
           echo "❌ Secret WEBAPI_PROJECT_NAME is missing."
-          echo "➡️ Go to settings > Actions secrets and variables > Actions to create it."
+          echo "➡️ Maak hem aan bij Settings > Actions secrets and variables > Actions."
           exit 1
 
   build:
-    name: 🏗️ Build & Test WebApi
     runs-on: ubuntu-latest
     needs: check
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+      - uses: actions/checkout@v4
 
       - name: Setup .NET
         uses: actions/setup-dotnet@v4
@@ -86,7 +83,6 @@ jobs:
           path: ${{ env.PUBLISH_DIRECTORY }}
 
   deploy:
-    name: 🚀 Deploy to Azure App Service
     runs-on: ubuntu-latest
     needs: [check, build]
     steps:
@@ -107,46 +103,55 @@ jobs:
                 publishUrl="${{ secrets.AZURE_WEBAPP_NAME }}.scm.azurewebsites.net:443"
                 userName="${{ secrets.AZURE_WEBAPP_PUBLISH_USERNAME }}"
                 userPWD="${{ secrets.AZURE_WEBAPP_PUBLISH_PASSWORD }}"
-                destinationAppUrl="https://${{ secrets.AZURE_WEBAPP_NAME }}.azurewebsites.net" />
+                destinationAppUrl="http://${{ secrets.AZURE_WEBAPP_NAME }}.azurewebsites.net"
+                SQLServerDBConnectionString=""
+                mySQLDBConnectionString=""
+                hostingProviderForumLink=""
+                controlPanelLink="https://portal.azure.com"
+                webSystem="WebSites">
+                <databases />
+              </publishProfile>
             </publishData>
           package: '${{ env.PUBLISH_DIRECTORY }}'
-          clean: true
+
   automated-api-tests:
-      runs-on: ubuntu-latest
-      needs: [check, build, deploy]
-      steps:
-        - uses: actions/checkout@v4
-        - name: Install Postman CLI
-          run: |
-            curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
-        - name: Login to Postman CLI
-          run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
-        - name: Run API tests
-          run: |
-            attempts=0
-            max_attempts=3
-            success=false
-            failed=false  # Ensure failed is initialized to false
-            
-            while [ $attempts -lt $max_attempts ]; do
-              echo "Attempt $((attempts+1)) of $max_attempts"
-              
-              # Run your Postman tests
-              postman collection run 28008990-3203de5a-449a-41c8-bba0-59c06e61f88a -e 28008990-b2df6f73-d29d-43e4-805b-f902f1bb455f -i 28008990-13704902-2232-40b1-bf9f-b8dc2bbe9539 -i 28008990-272f7a6c-4b38-4c27-bbb9-cb9f0d12b29e -i 28008990-6305f6b6-c3cc-426d-9628-f6aeac627ac7 -i 28008990-f5ca2ca1-f640-463d-a2db-35d202b36c18 -i 28008990-124ce121-495f-4780-9780-a24849f34c1a -i 28008990-027b3a27-3f95-44e0-a411-f3a0621f66ee -i 28008990-0d2971e7-4175-4ef4-bf51-2dbd95a48680 -i 28008990-108c09b0-6bde-4a8a-8d87-fc169a2eea8f -i 28008990-59e48ff6-ad86-497e-95b3-959ba2770b1a -i 28008990-79b03528-bba3-4e65-beac-234bbe388674 -i 28008990-011a72b1-57dd-4226-b785-5b6bc9ebb06f -i 28008990-cc2c3878-8cb7-4077-afc4-5c883426644b -i 28008990-337b7910-1a26-4959-95da-54d6dafe09af -i 28008990-41d8012a-b642-400d-a855-a15d01d030d5 -i 28008990-a119e78d-bf15-4757-b128-0b724fba9d7c -i 28008990-066c606e-62a4-42d3-805c-ca11aab6e0ed -i 28008990-2cd9027e-af95-4149-8f8d-ebdac9e865bb -i 28008990-815368bd-85b6-42c4-b2f3-d9f344381c20 -i 28008990-92505fe8-768d-4627-8512-3d0c104a0751 -i 28008990-b4ee7d20-4928-432f-876b-7c7a8eaf0066 -i 28008990-ee0a33d1-e320-4c8c-ad3c-c7dd5b2e1908 -i 28008990-09955bb6-f9ec-4aae-8d2c-eb3da0abbd4e -i 28008990-f0443889-1b70-4b5b-8eea-5ad29b8ed306            
-              # Check if tests failed
-              if [ "$failed" == "true" ]; then
-                echo "Tests failed. Retrying..."
-                attempts=$((attempts + 1))
-                failed=false  # Reset the failed flag for the next attempt
-              else
-                success=true
-                break
-              fi
-            done
-            
-            if [ "$success" == "false" ]; then
-              echo "API tests failed after $max_attempts attempts."
-              exit 1
+    runs-on: ubuntu-latest
+    needs: [check, build, deploy]
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Install Postman CLI
+        run: |
+          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
+
+      - name: Login to Postman CLI
+        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
+
+      - name: Run API tests
+        run: |
+          attempts=0
+          max_attempts=3
+          success=false
+          failed=false
+
+          while [ $attempts -lt $max_attempts ]; do
+            echo "Attempt $((attempts+1)) of $max_attempts"
+
+            postman collection run 28008990-76415ac0-2fa4-4361-b5e2-b1c2d5d5fa7d -e 28008990-6676e215-bc7f-4320-9bc6-1a698cea2fde -i 28008990-fc5ca702-10b7-472d-9398-8e33c115eca4 -i 28008990-70611f6f-cc3e-4d3c-ab5d-d46f29d6e9e5 -i 28008990-787ed8bb-6413-4d19-b7cf-b6a862aede08 -i 28008990-760fe5aa-f051-4c66-a45d-fb3618c53798 -i 28008990-38e4ad59-8419-49c0-b226-7eac76ac97c4 -i 28008990-942087d0-527c-4783-8982-8ed53bb2a251 -i 28008990-f902bda6-bb83-4a3d-aa68-e41f4039f598 -i 28008990-002c7839-a211-4137-9593-2e6ce3a61d0c -i 28008990-d6ecdc97-c549-4752-8efa-e040ccfa76a4 -i 28008990-fad6f42b-e0b2-43c6-943e-52ed2f8b1cf6 -i 28008990-8e7a8bf1-b2e6-4be5-ae60-0c2869b1ef47 -i 28008990-12c91e0b-b21c-4844-86f4-39c3bf27d399 -i 28008990-fbd70164-ffac-48e6-a26d-44a539b0a2de -i 28008990-76748e04-4b3b-45b4-98be-e891f8dc764c -i 28008990-4c576931-0e60-4a43-a191-a23371c67be7 -i 28008990-e107d157-608f-4260-8870-dcf44c011cba -i 28008990-0d841059-4108-4f8c-b04f-fbeb44cd062f -i 28008990-3aff7833-e995-43d9-85c9-2a43b0df1a00 -i 28008990-a8a39c7c-5e38-4083-830c-fb96f7064543 -i 28008990-0e52c500-3d3c-430d-917a-a633940d9ecc -i 28008990-092fda78-5bca-4420-a401-15006ca1fee3 -i 28008990-2d52fe39-6cc9-4dc2-bbfe-f6ef70ce1db2 -i 28008990-97f40591-6cde-45ba-8d59-49d9e9ac8778
+
+            if [ "$failed" == "true" ]; then
+              echo "Tests failed. Retrying..."
+              attempts=$((attempts + 1))
+              failed=false
             else
-              echo "API tests passed successfully after $attempts attempts."
+              success=true
+              break
             fi
+          done
+
+          if [ "$success" == "false" ]; then
+            echo "API tests failed after $max_attempts attempts."
+            exit 1
+          else
+            echo "API tests passed successfully after $attempts attempts."
+          fi
